#!/bin/sh
base_dir="$HOME/src/guile/"
dirs=("rde/src" "nonguix" "farg")
for dir in ${dirs[@]}; do
  local_paths+="${base_dir}${dir}:"
done
GUILE_LOAD_PATH="src:$local_paths${GUILE_LOAD_PATH:+:}$GUILE_LOAD_PATH"
GUILE_LOAD_COMPILED_PATH="src:$local_paths${GUILE_LOAD_COMPILED_PATH:+:}$GUILE_LOAD_COMPILED_PATH"
export GUILE_LOAD_COMPILED_PATH GUILE_LOAD_PATH

exec "$@"
